admin/src/main/java/org/goodiemania/seshat/data/models/Item.java
package org.goodiemania.seshat.data.models;

import java.util.Map;

public class Item {
    private final String id;
    private final Work work;
    private final Map<String, Object> metaData;

    /**
     * Constructs a new Item given the field parameters.
     *
     * @param id       The ID of the Item
     * @param work     The associated work for this item
     * @param metaData The associated Metadata for this item
     */
    public Item(final String id, final Work work, final Map<String, Object> metaData) {
        this.id = id;
        this.work = work;
        this.metaData = metaData;
    }

    public String getId() {
        return id;
    }

    public Work getWork() {
        return work;
    }

    public Map<String, Object> getMetaData() {
        return metaData;
    }

    public String getName() {
        return work.getAttributes().get(work.getWorkType().getAttributeName()).toString();
    }

    public String getDesc() {
        return work.getAttributes().get(work.getWorkType().getAttributeDesc()).toString();
    }
}

admin/src/main/webapp/WEB-INF/tags/AddAttributeValue.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://goodiemania.org/seshat/taglib" xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<!--@elvariable id="attribute" type="org.goodiemania.seshat.frontend.models.addwork.AddWorkField"-->

<h:body>
    <ui:composition>
        <s:inputSelectOne id="selectDataSource" label="#{attribute.fieldName}" value="#{attribute.value}">
            <f:selectItems value="#{attribute.possibleValues}" var="_type"
                           itemValue="#{_type}" itemLabel="#{_type.value} (#{_type.sources})"/>
            <f:selectItem noSelectionOption="true" itemLabel=""
                          itemValue=""/>
        </s:inputSelectOne>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/AddListAttributeValue.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://goodiemania.org/seshat/taglib" xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<!--@elvariable id="attribute" type="org.goodiemania.seshat.frontend.models.addwork.AddWorkField"-->

<h:body>
    <ui:composition>
        <s:inputSelectMany id="selectDataSource" label="#{attribute.fieldName}" value="#{attribute.value}">
            <f:selectItems value="#{attribute.possibleValues}" var="_type"
                           itemValue="#{_type}" itemLabel="#{_type.value} (#{_type.sources})"/>
        </s:inputSelectMany>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/card.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<!--@elvariable id="title" type="java.lang.String"-->
<!--@elvariable id="styleClass" type="java.lang.String"-->

<h:body>
    <ui:composition>
        <div class="#{not empty styleClass ? styleClass : 'col-xl-6'}">
            <div class="card shadow mb-4">
                <ui:fragment rendered="#{not empty title}">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">#{title}</h6>
                    </div>
                </ui:fragment>
                <div class="card-body">
                    <ui:insert/>
                </div>
            </div>
        </div>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/editAttributeValue.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://goodiemania.org/seshat/taglib"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<!--@elvariable id="editedValue" type="org.goodiemania.seshat.frontend.models.Attribute"-->

<h:body>
    <ui:composition>
        <ui:fragment rendered="#{editedValue.attribute.type eq 'STRING'}">
            <s:inputField id="metadata" value="#{editedValue.value}" label="#{editedValue.attribute.name}"/>
        </ui:fragment>
        <ui:fragment rendered="#{editedValue.attribute.type eq 'LIST'}">
            <ui:repeat value="#{editedValue.value}" var="_iVar">
                <s:inputField id="multiMetadata" value="#{_iVar}" label="#{editedValue.attribute.name}" readOnly="true">
                    <div class="input-group-append">
                        <h:commandButton action="#{editedValue.removeListValue(_iVar)}"
                                         value="Remove"
                                         styleClass="btn btn-outline-secondary">
                            <f:ajax execute="@form" render="@form"/>
                        </h:commandButton>
                    </div>
                </s:inputField>
            </ui:repeat>
            <s:inputField id="newMultiMetadata" value="#{editedValue.newListValue}" label="#{editedValue.attribute.name}">
                <div class="input-group-append">
                    <h:commandButton action="#{editedValue.addNewListValue()}"
                                     value="Add"
                                     styleClass="btn btn-outline-secondary">
                        <f:ajax execute="@form" render="@form"/>
                    </h:commandButton>
                </div>
            </s:inputField>
        </ui:fragment>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/form.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
>
<!--@elvariable id="id" type="java.lang.String"-->

<h:body>
    <ui:composition>
        <o:form useRequestURI="true" styleClass="form-group" id="#{empty id ? 'requestForm' : id}">
            <ui:insert/>
        </o:form>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/inputField.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
>
<!--@elvariable id="id" type="java.lang.String"-->
<!--@elvariable id="label" type="java.lang.String"-->
<!--@elvariable id="placeholder" type="java.lang.String"-->
<!--@elvariable id="value" type="java.lang.String"-->
<!--@elvariable id="readOnly" type="java.lang.Boolean"-->

<h:body>
    <ui:composition>
        <div class="input-group mb-3">
            <ui:fragment rendered="#{not empty label}">
                <div class="input-group-prepend">
                    <h:outputLabel id="#{id}Label" for="#{id}" value="#{label}" styleClass="input-group-text"/>
                </div>
            </ui:fragment>

            <h:inputText id="#{id}" styleClass="form-control"
                         a:placeholder="#{empty placeholder ? null : placeholder}"
                         value="#{value}"
                         readonly="#{empty readOnly ? false : readOnly}"
            />


            <ui:insert/>
        </div>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/inputSelectMany.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<!--@elvariable id="label" type="java.lang.String"-->
<!--@elvariable id="id" type="java.lang.String"-->
<!--@elvariable id="value" type="java.lang.Object"-->
<!--@elvariable id="readOnly" type="java.lang.Boolean"-->

<h:body>
    <ui:composition>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label for="#{id}"
                       id="#{id}Label"
                       class="input-group-text">
                    #{label}
                </label>
            </div>
            <h:selectManyListbox value="#{value}"
                             id="#{id}"
                             styleClass="custom-select"
                             readonly="#{empty readOnly ? false : readOnly}">
                <ui:insert/>
            </h:selectManyListbox>
        </div>
        <h:message for="${id}" id="#{id}Message" styleClass="alert alert-danger"/>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/inputSelectOne.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<!--@elvariable id="label" type="java.lang.String"-->
<!--@elvariable id="id" type="java.lang.String"-->
<!--@elvariable id="value" type="java.lang.Object"-->
<!--@elvariable id="readOnly" type="java.lang.Boolean"-->

<h:body>
    <ui:composition>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label for="#{id}"
                       id="#{id}Label"
                       class="input-group-text">
                    #{label}
                </label>
            </div>
            <h:selectOneMenu value="#{value}"
                             id="#{id}"
                             styleClass="custom-select"
                             readonly="#{empty readOnly ? false : readOnly}">
                <ui:insert/>
            </h:selectOneMenu>
        </div>
        <h:message for="${id}" id="#{id}Message" styleClass="alert alert-danger"/>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/inputTextArea.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
>
<!--@elvariable id="id" type="java.lang.String"-->
<!--@elvariable id="label" type="java.lang.String"-->
<!--@elvariable id="placeholder" type="java.lang.String"-->
<!--@elvariable id="value" type="java.lang.String"-->
<!--@elvariable id="readOnly" type="java.lang.Boolean"-->

<h:body>
    <ui:composition>
        <div class="input-group mb-3">
            <ui:fragment rendered="#{not empty label}">
                <div class="input-group-prepend">
                    <h:outputLabel id="#{id}Label" for="#{id}" value="#{label}" styleClass="input-group-text"/>
                </div>
            </ui:fragment>

            <h:inputTextarea id="#{id}" styleClass="form-control"
                         a:placeholder="#{empty placeholder ? null : placeholder}"
                         value="#{value}"
                         readonly="#{empty readOnly ? false : readOnly}"
            />


            <ui:insert/>
        </div>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/row.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<!--@elvariable id="rendered" type="java.lang.Boolean"-->
<h:body>
    <ui:composition>
        <!-- Content Row -->
        <h:panelGroup layout="block" styleClass="row" rendered="#{empty rendered ? true : rendered}">
            <ui:insert/>
        </h:panelGroup>
    </ui:composition>
</h:body>
</html>

admin/src/main/webapp/WEB-INF/tags/viewAttributeValue.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://goodiemania.org/seshat/taglib"
>
<!--@elvariable id="value" type="org.goodiemania.seshat.frontend.models.Attribute"-->

<h:body>
    <ui:composition>
        <ui:fragment rendered="#{value.attribute.type eq 'STRING' and not empty value.value}">
            <s:row>
                <dt class="col-sm-3">#{value.attribute.name}</dt>
                <dd class="col-sm-9">#{value.value}</dd>
            </s:row>
        </ui:fragment>
        <ui:fragment rendered="#{value.attribute.type eq 'LIST' and not value.value.isEmpty()}">
            <s:row>
                <dt class="col-sm-3">#{value.attribute.name}</dt>
                <dd class="col-sm-9"><ui:repeat value="#{value.value}" var="_iVar">
                    #{_iVar};
                </ui:repeat></dd>
            </s:row>
        </ui:fragment>
    </ui:composition>
</h:body>
</html>