admin/src/main/java/org/goodiemania/seshat/frontend/add/AddController.java
package org.goodiemania.seshat.frontend.add;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.enterprise.context.Conversation;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.frontend.NavigationController;

@Named
public class AddController {
    @Inject
    private WorkDao workDao;

    @Inject
    private NavigationController navigationController;

    @Inject
    private Conversation conversation;

    @Inject
    private InitAddBean initAddBean;

    @Inject
    private SelectDataSourceBean selectDataSourceBean;

    @Inject
    private ManageImportsController importsController;

    /**
     * Begin add process via controller.
     *
     * @return Redirection string
     */
    public String addViaController() {
        if (conversation.isTransient()) {
            conversation.begin();
        }

        String searchType = initAddBean.getConnectorSearchType();
        List<String> searchTerms = Arrays.stream(initAddBean.getConnectorSearchTerm().split(","))
                .flatMap(s -> Arrays.stream(s.split("\\r?\\n")))
                .collect(Collectors.toList());

        return importsController.start(initAddBean.getWorkType(), searchType, searchTerms);
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/add/InitAddBean.java
package org.goodiemania.seshat.frontend.add;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.data.misc.ConnectorInfo;
import org.goodiemania.seshat.data.models.WorkType;
import org.goodiemania.seshat.frontend.connectors.Connector;
import org.goodiemania.seshat.frontend.connectors.ConnectorsController;

@Named
@ViewScoped
public class InitAddBean implements Serializable {
    @Inject
    private WorkDao workDao;

    @Inject
    private ConnectorsController connectorsController;

    private List<WorkType> availableWorkTypes;
    private WorkType workType;
    private String connectorSearchType;
    private String connectorSearchTerm;

    @PostConstruct
    public void init() {
        availableWorkTypes = workDao.getAllWorkTypes();
    }

    public List<WorkType> getAvailableWorkTypes() {
        return availableWorkTypes;
    }

    public void setAvailableWorkTypes(final List<WorkType> availableWorkTypes) {
        this.availableWorkTypes = availableWorkTypes;
    }

    public WorkType getWorkType() {
        return workType;
    }

    public void setWorkType(final WorkType workType) {
        this.workType = workType;
    }

    public ConnectorInfo getConnectorInfo() {
        return workType.getConnectorInfo().orElse(null);
    }

    public Connector getConnector() {
        return connectorsController.getByName(getConnectorInfo().getName()).orElse(null);
    }

    public String getConnectorSearchType() {
        return connectorSearchType;
    }

    public void setConnectorSearchType(final String connectorSearchType) {
        this.connectorSearchType = connectorSearchType;
    }

    public String getConnectorSearchTerm() {
        return connectorSearchTerm;
    }

    public void setConnectorSearchTerm(final String connectorSearchTerm) {
        this.connectorSearchTerm = connectorSearchTerm;
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/add/SelectImportOptionsBean.java
package org.goodiemania.seshat.frontend.add;

import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;
import org.goodiemania.seshat.data.models.Work;

@Named
@ConversationScoped
public class SelectImportOptionsBean implements Serializable {
    private List<Work> possibleWorks;

    public List<Work> getPossibleWorks() {
        return possibleWorks;
    }

    public void setPossibleWorks(final List<Work> possibleWorks) {
        this.possibleWorks = possibleWorks;
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/worktypes/AddNewTypeController.java
package org.goodiemania.seshat.frontend.worktypes;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;
import org.apache.commons.lang3.StringUtils;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.data.misc.WorkTypeField;
import org.omnifaces.util.Faces;

@Named
@RequestScoped
public class AddNewTypeController {
    @Inject
    private AddNewTypeBean addNewTypeBean;

    @Inject
    private WorkDao workDao;


    public void removeAttribute(final WorkTypeField attribute) {
        addNewTypeBean.getAttributes().remove(attribute);
    }


    public void removeMetadata(final WorkTypeField metadata) {
        addNewTypeBean.getMetadata().remove(metadata);
    }

    /**
     * Adds the currently entered attribute type to the bean.
     */
    public void addAttribute() {
        if (StringUtils.isNotBlank(addNewTypeBean.getNewAttrbName())) {
            WorkTypeField newAttribute = new WorkTypeField(
                    addNewTypeBean.getNewAttrbName(),
                    addNewTypeBean.getNewAttrbType());
            addNewTypeBean.getAttributes().add(newAttribute);
            addNewTypeBean.resetNewAttribute();
        }
    }

    /**
     * Adds the currently entered metadata type to the bean.
     */
    public void addMetadata() {
        if (StringUtils.isNotBlank(addNewTypeBean.getNewMetaName())) {
            WorkTypeField newAttribute = new WorkTypeField(
                    addNewTypeBean.getNewMetaName(),
                    addNewTypeBean.getNewMetaType());
            addNewTypeBean.getMetadata().add(newAttribute);
            addNewTypeBean.resetNewMetadata();
        }
    }

    /**
     * Saves Whatever is currently in the add new type bean.
     *
     * @return String to redirect the browser with
     */
    public String save() {
        workDao.save(addNewTypeBean.toWorkType());
        addNewTypeBean.reset();

        Faces.getContext().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, "New Work type added", "")
        );
        Faces.getExternalContext().getFlash().setKeepMessages(true);

        return "browse?faces-redirect=true";
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/worktypes/BrowseAllTypesBean.java
package org.goodiemania.seshat.frontend.worktypes;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.data.models.WorkType;

@Named
@RequestScoped
public class BrowseAllTypesBean implements Serializable {
    @Inject
    private WorkDao workDao;
    private List<WorkType> workTypes;

    @PostConstruct
    public void init() {
        workTypes = workDao.getAllWorkTypes();
    }

    public List<WorkType> getWorkTypes() {
        return workTypes;
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/worktypes/ViewTypeBean.java
package org.goodiemania.seshat.frontend.worktypes;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.misc.ConnectorInfo;
import org.goodiemania.seshat.data.misc.WorkTypeField;
import org.goodiemania.seshat.data.models.WorkType;
import org.goodiemania.seshat.frontend.connectors.Connector;
import org.goodiemania.seshat.frontend.connectors.ConnectorsController;
import org.goodiemania.seshat.frontend.worktypes.model.ChooseConnectorSearchFields;
import org.goodiemania.seshat.frontend.worktypes.model.ConnectorMapping;

@Named
@ConversationScoped
public class ViewTypeBean implements Serializable {
    @Inject
    private ConnectorsController connectorsController;

    private String id;
    private String name;
    private String description;
    private List<WorkTypeField> attributes;
    private List<WorkTypeField> metadata;
    private String newAttrbName;
    private WorkTypeField.Type newAttrbType;
    private String newMetaName;
    private WorkTypeField.Type newMetaType;
    private String attributeName;
    private String attributeDesc;
    private Connector connector;
    private List<ConnectorMapping> connectorMappings;
    private String newConnectConnectName;
    private String newConnectWorkName;
    private List<ChooseConnectorSearchFields> searchFields;
    private String newSearchId;
    private List<String> newSearchFields;

    /**
     * Load the specified work type into the bean.
     *
     * @param type WorkType object
     */
    public void load(final WorkType type) {
        this.id = type.getId();
        this.name = type.getName();
        this.description = type.getDescription();
        this.attributes = type.getAttributes();
        this.metadata = type.getMetadata();
        this.attributeName = type.getAttributeName();
        this.attributeDesc = type.getAttributeDesc();

        type.getConnectorInfo().ifPresent(connectorInfo ->
                connectorsController.getByName(connectorInfo.getName()).ifPresent(foundConnector -> {
                    this.connector = foundConnector;
                    this.connectorMappings = connectorInfo.getConnectorMapping().stream()
                            .map(connectorMapping -> ConnectorMapping.of(
                                    connectorMapping.getConnectorName(),
                                    connectorMapping.getWorkName()))
                            .collect(Collectors.toList());
                    this.searchFields = connectorInfo.getSearchMapping()
                            .entrySet()
                            .stream()
                            .map((entry) -> ChooseConnectorSearchFields.of(entry.getKey(), entry.getValue()))
                            .collect(Collectors.toList());
                }));

        if (connectorMappings == null) {
            this.connectorMappings = new ArrayList<>();
        }

        resetNewAttribute();
        resetNewMetadata();
        resetNewConnect();
        resetNewConnectSearch();
    }

    /**
     * Reset the new attribute values back to default values.
     */
    public void resetNewAttribute() {
        newAttrbName = "";
        newAttrbType = WorkTypeField.Type.STRING;
    }

    /**
     * Reset the new metadata values back to default values.
     */
    public void resetNewMetadata() {
        newMetaName = "";
        newMetaType = WorkTypeField.Type.STRING;
    }

    /**
     * Reset the new metadata values back to default values.
     */
    public void resetNewConnect() {
        newConnectConnectName = "";
        newConnectWorkName = "";
    }


    /**
     * Reset the connector search fields.
     */
    public void resetNewConnectSearch() {
        newSearchId = "";
        newSearchFields = new ArrayList<>();
    }

    public WorkTypeField.Type[] getAttributeTypes() {
        return WorkTypeField.Type.values();
    }

    /**
     * Returns a list of the selected connector fields.
     *
     * @return Returns a list of connector fields
     */
    public List<String> getConnectorFields() {
        return Optional.ofNullable(connector)
                .map(Connector::getFields)
                .map(Map::keySet)
                .stream()
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
    }

    /**
     * Returns a list of the selected mapping fields.
     *
     * @return Returns a list of mapping fields
     */
    public List<String> getConnectorMappingFields() {
        WorkTypeField.Type type = Optional.ofNullable(connector)
                .map(Connector::getFields)
                .map(stringTypeMap -> stringTypeMap.get(newConnectConnectName))
                .orElse(null);
        return attributes.stream()
                .filter(workTypeField -> workTypeField.getType().equals(type))
                .map(WorkTypeField::getName)
                .collect(Collectors.toList());
    }

    /**
     * Returns a list of the selected mapping fields.
     *
     * @return Returns a list of mapping fields
     */
    public List<String> getConnectorSearchFields() {
        Function<String, Boolean> hasSearchBeenUsed = s -> !searchFields.stream()
                .map(ChooseConnectorSearchFields::getSearchId)
                .collect(Collectors.toSet())
                .contains(s);

        return Optional.ofNullable(connector)
                .map(Connector::getSearchTypes)
                .stream()
                .flatMap(Collection::stream)
                .filter(hasSearchBeenUsed::apply)
                .collect(Collectors.toList());
    }

    /**
     * Returns a list of the selected mapping fields.
     *
     * @return Returns a list of mapping fields
     */
    public List<String> getConnectorSearchMappingFields() {
        return attributes.stream()
                .map(WorkTypeField::getName)
                .collect(Collectors.toList());
    }

    public List<Connector> getAllConnectors() {
        return connectorsController.getConnectors();
    }

    /**
     * Creates a ItemType object given this beans fields.
     *
     * @return The new ItemType
     */
    public WorkType toWorkType() {
        ConnectorInfo connectorInfo = null;

        if (connector != null) {
            HashMap<String, List<String>> searchFieldMap = new HashMap<>();
            searchFields.forEach(fields -> searchFieldMap.put(fields.getSearchId(), fields.getSearchFields()));

            connectorInfo = new ConnectorInfo(
                    connector.getName(),
                    this.connectorMappings.stream()
                            .map(connectorMapping -> new org.goodiemania.seshat.data.misc.ConnectorMapping(
                                    connectorMapping.getConnectorName(),
                                    connectorMapping.getWorkName()))
                            .collect(Collectors.toList()),
                    searchFieldMap);
        }

        return new WorkType(
                id,
                name,
                description,
                attributes,
                metadata,
                attributeName,
                attributeDesc,
                connectorInfo);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<WorkTypeField> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<WorkTypeField> attributes) {
        this.attributes = attributes;
    }

    public String getNewAttrbName() {
        return newAttrbName;
    }

    public void setNewAttrbName(final String newAttrbName) {
        this.newAttrbName = newAttrbName;
    }

    public WorkTypeField.Type getNewAttrbType() {
        return newAttrbType;
    }

    public void setNewAttrbType(final WorkTypeField.Type newAttrbType) {
        this.newAttrbType = newAttrbType;
    }

    public String getNewMetaName() {
        return newMetaName;
    }

    public void setNewMetaName(final String newMetaName) {
        this.newMetaName = newMetaName;
    }

    public WorkTypeField.Type getNewMetaType() {
        return newMetaType;
    }

    public void setNewMetaType(final WorkTypeField.Type newMetaType) {
        this.newMetaType = newMetaType;
    }

    public List<WorkTypeField> getMetadata() {
        return metadata;
    }

    public void setMetadata(final List<WorkTypeField> metadata) {
        this.metadata = metadata;
    }


    public String getAttributeName() {
        return attributeName;
    }

    public void setAttributeName(final String attributeName) {
        this.attributeName = attributeName;
    }

    public String getAttributeDesc() {
        return attributeDesc;
    }

    public void setAttributeDesc(final String attributeDesc) {
        this.attributeDesc = attributeDesc;
    }

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public Connector getConnector() {
        return connector;
    }

    public void setConnector(final Connector connector) {
        this.connector = connector;
    }

    public List<ConnectorMapping> getConnectorMappings() {
        return connectorMappings;
    }

    public void setConnectorMappings(List<ConnectorMapping> connectorMappings) {
        this.connectorMappings = connectorMappings;
    }

    public String getNewConnectConnectName() {
        return newConnectConnectName;
    }

admin/src/main/webapp/workTypes/browse.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/_base.xhtml"
                xmlns:s="http://goodiemania.org/seshat/taglib">

    <ui:define name="title">Browse Item Types</ui:define>

    <ui:define name="body">
        <s:row>
            <s:card title="All types" styleClass="col-xl-12">
                <s:form>
                    <h:dataTable value="#{browseAllTypesBean.workTypes}"
                                 styleClass="table table-striped"
                                 var="_p"
                                 width="100%"
                                 id="itemTypesTable">
                        <h:column>
                            <f:facet name="header">Name</f:facet>
                            <h:commandLink value="#{_p.name}" action="#{navigationController.viewWorkType(_p.id)}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Desription</f:facet>
                            <h:outputText value="#{_p.description}"/>
                        </h:column>
                    </h:dataTable>
                </s:form>
            </s:card>
        </s:row>
    </ui:define>
</ui:composition>

admin/src/main/webapp/workTypes/view.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:s="http://goodiemania.org/seshat/taglib"
                template="/WEB-INF/templates/_base.xhtml">

    <ui:define name="title">Browse Item Types</ui:define>

    <ui:define name="body">
        <h:form>
            <s:row>
                <s:card title="Details" styleClass="col-xl-12">
                    <s:inputField id="id" value="#{viewTypeBean.id}" label="ID" placeholder="ID"/>
                    <s:inputField id="name" value="#{viewTypeBean.name}" label="Name" placeholder="Name"/>
                    <s:inputField id="Description" value="#{viewTypeBean.description}" label="Description"
                                  placeholder="Description"/>
                    <s:inputSelectOne id="nameField" label="Name attribute field" value="#{viewTypeBean.attributeName}">
                        <f:selectItems value="#{viewTypeBean.attributes}" var="_type"
                                       itemValue="#{_type.name}" itemLabel="#{_type.name}"/>
                    </s:inputSelectOne>
                    <s:inputSelectOne id="descField" label="Description attribute field"
                                      value="#{viewTypeBean.attributeDesc}">
                        <f:selectItems value="#{viewTypeBean.attributes}" var="_type"
                                       itemValue="#{_type.name}" itemLabel="#{_type.name}"/>
                    </s:inputSelectOne>
                </s:card>
            </s:row>
            <s:row>
                <s:card title="Attributes" styleClass="col-xl-6">
                    <div>Attributes belong to a work, think authors of a book, published date, etc</div>
                    <ui:repeat value="#{viewTypeBean.attributes}" var="_value">
                        <s:inputField id="attribute" value="#{_value.name}" readOnly="true">
                            <div class="input-group-append">
                                <h:selectOneMenu value="#{_value.type}" style="color: rgb(108, 117, 125)"
                                                 disabled="true">
                                    <f:selectItems value="#{viewTypeBean.attributeTypes}" var="_type"
                                                   itemValue="#{_type}" itemLabel="#{_type}"/>
                                </h:selectOneMenu>
                                <h:commandButton action="#{viewTypeController.removeAttribute(_value)}"
                                                 value="Remove"
                                                 styleClass="btn btn-outline-secondary">
                                    <f:ajax execute="@form" render="@form"/>
                                </h:commandButton>
                            </div>
                        </s:inputField>
                    </ui:repeat>

                    <s:inputField id="newAttribute" value="#{viewTypeBean.newAttrbName}" label="New Attribute"
                                  placeholder="name">
                        <div class="input-group-append">
                            <h:selectOneMenu value="#{viewTypeBean.newAttrbType}" style="color: rgb(108, 117, 125)">
                                <f:selectItems value="#{viewTypeBean.attributeTypes}" var="_type" itemValue="#{_type}"
                                               itemLabel="#{_type.description}"/>
                            </h:selectOneMenu>
                            <h:commandButton action="#{viewTypeController.addAttribute}"
                                             value="Add"
                                             styleClass="btn btn-outline-secondary">
                                <f:ajax execute="@form" render="@form"/>
                            </h:commandButton>
                        </div>
                    </s:inputField>
                </s:card>
                <s:card title="Metadata" styleClass="col-xl-6">
                    <div>Metadata belongs to a item (an instance of a work), think missing pages, skipping record, etc</div>
                    <ui:repeat value="#{viewTypeBean.metadata}" var="_value">
                        <s:inputField id="metadata" value="#{_value.name}" readOnly="true">
                            <div class="input-group-append">
                                <h:selectOneMenu value="#{_value.type}" style="color: rgb(108, 117, 125)"
                                                 disabled="true">
                                    <f:selectItems value="#{viewTypeBean.attributeTypes}" var="_type"
                                                   itemValue="#{_type}" itemLabel="#{_type.description}"/>
                                </h:selectOneMenu>
                                <h:commandButton action="#{viewTypeController.removeMetadata(_value)}"
                                                 value="Remove"
                                                 styleClass="btn btn-outline-secondary">
                                    <f:ajax execute="@form" render="@form"/>
                                </h:commandButton>
                            </div>
                        </s:inputField>
                    </ui:repeat>

                    <s:inputField id="newMetadata" value="#{viewTypeBean.newMetaName}" label="New Metadata"
                                  placeholder="name">
                        <div class="input-group-append">
                            <h:selectOneMenu value="#{viewTypeBean.newMetaType}" style="color: rgb(108, 117, 125)">
                                <f:selectItems value="#{viewTypeBean.attributeTypes}" var="_type" itemValue="#{_type}"
                                               itemLabel="#{_type.description}"/>
                            </h:selectOneMenu>
                            <h:commandButton action="#{viewTypeController.addMetadata}"
                                             value="Add"
                                             styleClass="btn btn-outline-secondary">
                                <f:ajax execute="@form" render="@form"/>
                            </h:commandButton>
                        </div>
                    </s:inputField>
                </s:card>
            </s:row>
            <s:row>
                <s:card styleClass="col-xl-12" title="Connector">
                    <s:inputSelectOne value="#{viewTypeBean.connector}" style="color: rgb(108, 117, 125)"
                                      id="connectorType" label="Connector">
                        <f:selectItem itemLabel="Blank" itemValue="#{null}"/>
                        <f:selectItems value="#{viewTypeBean.allConnectors}" var="_type"
                                       itemValue="#{_type}" itemLabel="#{_type.name}"/>
                        <f:ajax execute="@form" render="@form"/>
                    </s:inputSelectOne>
                </s:card>
                <ui:fragment rendered="#{viewTypeBean.connector ne null}">
                    <s:card styleClass="col-xl-12" title="Connector mapping">
                        <ui:repeat value="#{viewTypeBean.connectorMappings}" var="_mapping">
                            <s:inputField id="existingConnector" value="#{_mapping.connectorName}" readOnly="true"
                                          label="Connector // work field">
                                <h:inputText id="existingConnectorWorkMap" styleClass="form-control"
                                             value="#{_mapping.workName}" readonly="true"/>
                                <div class="input-group-append">
                                    <h:commandButton action="#{viewTypeController.removeConnectorMapping(_mapping)}"
                                                     value="Remove"
                                                     styleClass="btn btn-outline-secondary">
                                        <f:ajax execute="@form" render="@form"/>
                                    </h:commandButton>
                                </div>
                            </s:inputField>
                        </ui:repeat>
                        <s:inputSelectOne id="addNewConnectorMapping" label="Connector mapping"
                                          value="#{viewTypeBean.newConnectConnectName}">
                            <f:selectItem noSelectionOption="true" itemLabel="Select a connector field"
                                          itemValue="#{null}"/>
                            <f:selectItems value="#{viewTypeBean.connectorFields}" var="_type"
                                           itemValue="#{_type}" itemLabel="#{_type}"/>
                            <f:ajax execute="@form" render="@form"/>
                        </s:inputSelectOne>
                        <s:inputSelectOne id="addNewMapping" label="Connector mapping"
                                          value="#{viewTypeBean.newConnectWorkName}">
                            <f:selectItems value="#{viewTypeBean.connectorMappingFields}" var="_type"
                                           itemValue="#{_type}" itemLabel="#{_type}"/>
                        </s:inputSelectOne>

                        <h:commandButton action="#{viewTypeController.addConnectorMapping}"
                                         value="Add connector mapping"
                                         styleClass="btn btn-outline-secondary">
                            <f:ajax execute="@form" render="@form"/>
                        </h:commandButton>
                    </s:card>
                    <s:card styleClass="col-xl-12" title="Connector search">
                        <ui:repeat value="#{viewTypeBean.searchFields}" var="_field">
                            <s:inputField id="exisitingSearchField" value="#{_field.searchId} - #{_field.searchFields}" readOnly="true"
                                          label="Search field">

                                <div class="input-group-append">
                                    <h:commandButton action="#{viewTypeController.removeConnectorSearch(_field)}"
                                                     value="Remove"
                                                     styleClass="btn btn-outline-secondary">
                                        <f:ajax execute="@form" render="@form"/>
                                    </h:commandButton>
                                </div>
                            </s:inputField>
                        </ui:repeat>
                        <s:inputSelectOne id="addNewSearchMappingConnector" label="Ttype"
                                          value="#{viewTypeBean.newSearchId}">
                            <f:selectItems value="#{viewTypeBean.connectorSearchFields}" var="_type"
                                           itemValue="#{_type}" itemLabel="#{_type}"/>
                        </s:inputSelectOne>
                        <s:inputSelectMany id="addNewSearchMappingMapping" label="Fields"
                                           value="#{viewTypeBean.newSearchFields}">
                            <f:selectItems value="#{viewTypeBean.connectorSearchMappingFields}" var="_type"
                                           itemValue="#{_type}" itemLabel="#{_type}"/>
                        </s:inputSelectMany>

                        <h:commandButton action="#{viewTypeController.addConnectorSearch}"
                                         value="Add connector search"
                                         styleClass="btn btn-outline-secondary">
                            <f:ajax execute="@form" render="@form"/>
                        </h:commandButton>
                    </s:card>
                </ui:fragment>
            </s:row>
            <s:row>
                <s:card styleClass="col-xl-12">
                    <h:commandButton action="#{viewTypeController.save}"
                                     value="Save"
                                     styleClass="btn btn-outline-secondary"/>
                </s:card>
            </s:row>
        </h:form>
    </ui:define>
</ui:composition>