admin/src/main/java/org/goodiemania/seshat/data/models/Item.java
package org.goodiemania.seshat.data.models;

import java.util.Map;

public class Item {
    private final String id;
    private final Work work;
    private final Map<String, Object> metaData;

    /**
     * Constructs a new Item given the field parameters.
     *
     * @param id       The ID of the Item
     * @param work     The associated work for this item
     * @param metaData The associated Metadata for this item
     */
    public Item(final String id, final Work work, final Map<String, Object> metaData) {
        this.id = id;
        this.work = work;
        this.metaData = metaData;
    }

    public String getId() {
        return id;
    }

    public Work getWork() {
        return work;
    }

    public Map<String, Object> getMetaData() {
        return metaData;
    }

    public String getName() {
        return work.getAttributes().get(work.getWorkType().getAttributeName()).toString();
    }

    public String getDesc() {
        return work.getAttributes().get(work.getWorkType().getAttributeDesc()).toString();
    }
}

admin/src/main/java/org/goodiemania/seshat/authentication/SessionBean.java
package org.goodiemania.seshat.authentication;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.data.misc.ConnectorInfo;
import org.goodiemania.seshat.data.misc.ConnectorMapping;
import org.goodiemania.seshat.data.misc.User;
import org.goodiemania.seshat.data.misc.WorkTypeField;
import org.goodiemania.seshat.data.models.WorkType;
import org.slf4j.Logger;

@Named
@SessionScoped
public class SessionBean implements Serializable {
    @Inject
    private WorkDao workDao;

    @Inject
    private Logger logger;

    private User user;

    /**
     * Attempts to load a user based on a given UserID.
     *
     * @param userId UserId to attempt to load
     */
    public void loadUser(String userId) {
        this.user = new User(userId, "Goodie", true, true, true);

        if (workDao.getAllWorkTypes().isEmpty()) {
            logger.info("Initializing database");

            WorkType bookWorkType = new WorkType(
                    UUID.randomUUID().toString(),
                    "Book",
                    "This is a book desc",
                    List.of(
                            new WorkTypeField("series-title", WorkTypeField.Type.STRING),
                            new WorkTypeField("title", WorkTypeField.Type.STRING),
                            new WorkTypeField("sub-title", WorkTypeField.Type.STRING),
                            new WorkTypeField("description", WorkTypeField.Type.STRING),
                            new WorkTypeField("Author(s)", WorkTypeField.Type.LIST),
                            new WorkTypeField("ISBN10", WorkTypeField.Type.STRING),
                            new WorkTypeField("ISBN13", WorkTypeField.Type.STRING)
                    ),
                    List.of(
                            new WorkTypeField("quality", WorkTypeField.Type.STRING)
                    ),
                    "title",
                    "description",
                    new ConnectorInfo(
                            "Book Information",
                            List.of(
                                    new ConnectorMapping("series-title", "series-title"),
                                    new ConnectorMapping("title", "title"),
                                    new ConnectorMapping("sub-title", "sub-title"),
                                    new ConnectorMapping("description", "description"),
                                    new ConnectorMapping("ISBN10", "ISBN10"),
                                    new ConnectorMapping("ISBN13", "ISBN13"),
                                    new ConnectorMapping("author", "Author(s)")
                            ),
                            Map.of("ISBN", List.of("ISBN10", "ISBN13"))
                    ));
            workDao.save(bookWorkType);
            workDao.save(new WorkType(
                    UUID.randomUUID().toString(),
                    "Vinyl Record",
                    "Vinyl, the old school hipster way to play music",
                    List.of(
                            new WorkTypeField("title", WorkTypeField.Type.STRING),
                            new WorkTypeField("description", WorkTypeField.Type.STRING),
                            new WorkTypeField("Artist(s)", WorkTypeField.Type.LIST)
                    ),
                    List.of(
                            new WorkTypeField("quality", WorkTypeField.Type.STRING)
                    ),
                    "title",
                    "description",
                    null));

            logger.info("Finished initializing database");
        }
    }

    public void logout() {
        this.user = null;
    }

    public User getUser() {
        return user;
    }

    public boolean isItemReadOnly() {
        return !user.isCanEditItems();
    }

    public boolean isWorkReadOnly() {
        return !user.isCanEditWorkTypes();
    }

    public boolean isWorkTypeReadOnly() {
        return !user.isCanEditWorkTypes();
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/items/EditItemBean.java
package org.goodiemania.seshat.frontend.items;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;
import org.goodiemania.seshat.data.models.Item;
import org.goodiemania.seshat.data.models.Work;
import org.goodiemania.seshat.data.models.WorkType;
import org.goodiemania.seshat.frontend.models.Attribute;

@Named
@ConversationScoped
public class EditItemBean implements Serializable {
    private String id;
    private Work work;
    private List<Attribute> metadata = new ArrayList<>();
    private List<Attribute> attributes = new ArrayList<>();
    private WorkType workType;

    /**
     * Load the specified Item into the bean.
     *
     * @param item Item object
     */
    public void load(final Item item) {
        this.id = item.getId();
        this.work = item.getWork();
        this.workType = item.getWork().getWorkType();

        this.metadata = new ArrayList<>();
        this.attributes = new ArrayList<>();

        workType.getMetadata().forEach(attribute -> {
            Object value = item.getMetaData().getOrDefault(attribute.getName(), attribute.getType().getDefaultSupplier().get());
            metadata.add(new Attribute(attribute, value));
        });

        workType.getAttributes().forEach(attribute -> {
            Object value = item.getWork().getAttributes().getOrDefault(attribute.getName(), attribute.getType().getDefaultSupplier().get());
            attributes.add(new Attribute(attribute, value));
        });
    }

    public String getId() {
        return id;
    }

    public List<Attribute> getMetadata() {
        return metadata;
    }

    public List<Attribute> getAttributes() {
        return attributes;
    }

    public Work getWork() {
        return work;
    }

    /**
     * Converts Bean fields to Item.
     *
     * @return Converted Item
     */
    public Item toItem() {
        Map<String, Object> metadataMap = metadata.stream()
                .collect(Collectors.toMap(attribute -> attribute.getAttribute().getName(), Attribute::getValue));

        return new Item(id, work, metadataMap);
    }

    public String getName() {
        return work.getAttributes().get(workType.getAttributeName()).toString();
    }

    public String getDesc() {
        return work.getAttributes().get(workType.getAttributeDesc()).toString();
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/items/EditItemController.java
package org.goodiemania.seshat.frontend.items;

import java.io.Serializable;
import javax.inject.Inject;
import javax.inject.Named;
import org.goodiemania.seshat.data.WorkDao;
import org.goodiemania.seshat.frontend.NavigationController;
import org.slf4j.Logger;

@Named
public class EditItemController implements Serializable {
    @Inject
    private WorkDao workDao;

    @Inject
    private EditItemBean editItemBean;

    @Inject
    private Logger logger;

    @Inject
    private NavigationController navigationController;

    /**
     * Saves Whatever is currently in the edit item bean.
     *
     * @return String to redirect the browser with
     */
    public String save() {
        logger.info("Saving edited item");
        workDao.save(editItemBean.toItem());
        return navigationController.viewItem(editItemBean.getId());
    }
}

admin/src/main/java/org/goodiemania/seshat/frontend/items/ViewItemBean.java
package org.goodiemania.seshat.frontend.items;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;
import org.apache.commons.lang3.StringUtils;
import org.goodiemania.seshat.data.misc.WorkTypeField;
import org.goodiemania.seshat.data.models.Item;
import org.goodiemania.seshat.data.models.Work;
import org.goodiemania.seshat.data.models.WorkType;
import org.goodiemania.seshat.frontend.models.Attribute;

@Named
@ConversationScoped
public class ViewItemBean implements Serializable {
    private String id;
    private Work work;
    private List<Attribute> metadata = new ArrayList<>();
    private List<Attribute> attributes = new ArrayList<>();
    private WorkType workType;

    /**
     * Load the specified Item into the bean.
     *
     * @param item Item object
     */
    public void load(final Item item) {
        this.id = item.getId();
        this.work = item.getWork();
        this.workType = item.getWork().getWorkType();

        this.metadata = new ArrayList<>();
        this.attributes = new ArrayList<>();

        workType.getMetadata().forEach(attribute -> {
            Object value = item.getMetaData().getOrDefault(attribute.getName(), attribute.getType().getDefaultSupplier().get());
            metadata.add(new Attribute(attribute, value));
        });

        workType.getAttributes()
                .stream()
                .filter(this::isNotSpecialField)
                .forEach(attribute -> {
                    Object value = work.getAttributes().getOrDefault(attribute.getName(), attribute.getType().getDefaultSupplier().get());
                    attributes.add(new Attribute(attribute, value));
                });
    }

    private boolean isNotSpecialField(final WorkTypeField workTypeField) {
        return !StringUtils.equalsAny(workTypeField.getName(),
                workType.getAttributeName(),
                workType.getAttributeDesc());
    }

    public String getId() {
        return id;
    }

    public List<Attribute> getMetadata() {
        return metadata;
    }

    public List<Attribute> getAttributes() {
        return attributes;
    }

    public Work getWork() {
        return work;
    }

    public String getName() {
        return work.getAttributes().get(workType.getAttributeName()).toString();
    }

    public String getDesc() {
        return work.getAttributes().get(workType.getAttributeDesc()).toString();
    }
}

admin/src/main/webapp/item/edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:s="http://goodiemania.org/seshat/taglib"
                template="/WEB-INF/templates/_base.xhtml">

    <ui:define name="title">Browse Item Types</ui:define>

    <ui:define name="body">
        <h:form>
            <s:row>
                <s:card title="Details" styleClass="col-xl-12">
                    <s:inputField id="id" value="#{editItemBean.id}" label="ID"
                                  readOnly="true"/>

                    <ui:repeat value="#{editItemBean.metadata}" var="_value">
                        <s:editAttributeValue editedValue="#{_value}"/>
                    </ui:repeat>

                    <h:commandButton action="#{editItemController.save}"
                                     value="Save Item"
                                     styleClass="btn btn-outline-secondary"
                                     rendered="#{not sessionBean.itemReadOnly}"/>
                </s:card>
            </s:row>
            <s:row>
                <s:card styleClass="col-xl-12">
                    <ui:repeat value="#{editItemBean.attributes}" var="_value">
                        <s:viewAttributeValue value="#{_value}"/>
                    </ui:repeat>
                </s:card>
            </s:row>
        </h:form>
    </ui:define>
</ui:composition>

admin/src/main/webapp/item/view.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:s="http://goodiemania.org/seshat/taglib"
                template="/WEB-INF/templates/_base.xhtml">

    <ui:define name="title">Browse Item Types</ui:define>

    <ui:define name="body">
        <h:form>
            <s:row>
                <div class="col-xl-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">#{viewItemBean.name}</h6>
                        </div>
                    </div>
                </div>
            </s:row>
            <s:row>
                <s:card styleClass="col-xl-3">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <ui:repeat value="#{viewItemBean.work.imageIds}" var="_image" varStatus="_status">
                                <li data-target="#carouselExampleIndicators" data-slide-to="#{_status.index}"
                                    class="#{_status.index eq 0 ? 'active' : ''}"/>
                            </ui:repeat>
                        </ol>
                        <div class="carousel-inner">
                            <ui:repeat value="#{viewItemBean.work.imageIds}" var="_image" varStatus="_status">
                                <div class="carousel-item#{_status.index eq 0 ? ' active' : ''}">
                                    <img class="d-block mx-auto" src="/image/#{_image}" alt="Item image"/>
                                </div>
                            </ui:repeat>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true" style="filter: invert(100%);"/>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true" style="filter: invert(100%);"/>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </s:card>
                <s:card title="Details" styleClass="col-xl-6">
                    <div class="collapseModule">
                        <h3>#{viewItemBean.name}</h3>
                        <p class="collapse" id="collapseExample" aria-expanded="false">
                            #{viewItemBean.desc}
                        </p>
                        <a role="button" class="collapsed" data-toggle="collapse" href="#collapseExample"
                           aria-expanded="false" aria-controls="collapseExample"/>
                    </div>

                    <ui:repeat value="#{viewItemBean.metadata}" var="_value">
                        <s:viewAttributeValue value="#{_value}"/>
                    </ui:repeat>
                </s:card>
                <s:card title="Menu" styleClass="col-xl-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <h:commandLink value="Edit item"
                                           action="#{navigationController.editItem(viewItemBean.id)}"
                                           rendered="#{not sessionBean.itemReadOnly}"/>
                        </li>
                        <li class="list-group-item">
                            <h:commandLink value="View work"
                                           action="#{navigationController.viewWork(viewItemBean.work.id)}"/>
                        </li>
                        <li class="list-group-item">
                            <h:commandLink value="Edit work"
                                           action="#{navigationController.editWork(viewItemBean.work.id)}"
                                           rendered="#{not sessionBean.workReadOnly}"/>
                        </li>
                    </ul>
                </s:card>
            </s:row>
            <s:row>
                <s:card title="Work attributes" styleClass="col-xl-12">
                    <s:row>
                        <dt class="col-sm-3">ID</dt>
                        <dd class="col-sm-9">#{viewItemBean.id}</dd>
                    </s:row>
                    <s:row>
                        <dt class="col-sm-3">Work ID</dt>
                        <dd class="col-sm-9">#{viewItemBean.work.id}</dd>
                    </s:row>
                    <ui:repeat value="#{viewItemBean.attributes}" var="_value">
                        <s:viewAttributeValue value="#{_value}"/>
                    </ui:repeat>
                </s:card>
            </s:row>
        </h:form>
    </ui:define>
</ui:composition>